FROM php:7.3-apache

#RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN docker-php-ext-install pdo pdo_mysql
RUN a2enmod rewrite

RUN apt-get update && apt-get upgrade -y


COPY . /var/www/html/

EXPOSE 80